# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160120_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ['-date'], 'verbose_name': 'Blog page', 'verbose_name_plural': 'Blog pages'},
        ),
    ]
